/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.cfranc.irc.ui;

import java.awt.Image;
import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.cfranc.irc.impl.UserImpl;




/**
 * 
 * @author Administrateur
 */
public class UserCompte extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserImpl userConnect = null;
	private int mode; // 1 = Création - 2 - Consultation
	private String chemin = "";
	
	int getMode() {
		return mode;
	}

	void setMode(int mode) {
		this.mode = mode;
	}

	
	UserImpl getUserConnect() {
		return userConnect;
	}

	void setUserConnect(UserImpl u) {
		this.userConnect = u;
		txtLogin.setText(u.getLogin());
		txtNom.setText(u.getNom());
		txtPrenom.setText(u.getPrenom());
		txtPwd.setText(u.getPwd());
		affecterImage(u.getImageURI());
		txtLogin.setEditable(false);
		txtNom.setEditable(false);
		txtPrenom.setEditable(false);
		txtPwd.setEditable(false);
	}

	/**
	 * Creates new form CompteUser
	 */
	public UserCompte(int mode) {
		this.mode = mode;
		initComponents();
		setSize(350, 510);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtPwd = new javax.swing.JTextField();
		txtPrenom = new javax.swing.JTextField();
		txtNom = new javax.swing.JTextField();
		txtLogin = new javax.swing.JTextField();
		btnSelectionerImage = new javax.swing.JButton();
		pnlImage = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		btnValider = new javax.swing.JButton();

		jLabel3.setText("jLabel3");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Login :");

		jLabel2.setText("Nom : ");

		jLabel4.setText("Prénom :");

		jLabel5.setText("Mot de passe :");

		jLabel6.setText("Avatar :");

		txtPwd.setText("");

		txtPrenom.setText("");

		txtNom.setText("");

		btnSelectionerImage.setText("Sélectionner une image");
		btnSelectionerImage
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						btnSelectionerImageActionPerformed(evt);
					}
				});

		pnlImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1,
				1));

		// jLabel7lblImage.setText("jLabel7");

		javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(
				pnlImage);
		pnlImage.setLayout(pnlImageLayout);
		pnlImageLayout.setHorizontalGroup(pnlImageLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				pnlImageLayout.createSequentialGroup().addComponent(jLabel7)
						.addGap(0, 210, Short.MAX_VALUE)));
		pnlImageLayout.setVerticalGroup(pnlImageLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				pnlImageLayout.createSequentialGroup().addComponent(jLabel7)
						.addGap(0, 187, Short.MAX_VALUE)));

		jButton1.setText("Annuler");

		btnValider.setText("Valider");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(17, 17, 17)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(
																		jLabel2)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(1, 1, 1)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel6))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jButton1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										btnValider))
																				.addComponent(
																						btnSelectionerImage)
																				.addComponent(
																						txtPwd,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						147,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtLogin,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						193,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtNom)
																				.addComponent(
																						txtPrenom)
																				.addComponent(
																						pnlImage,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(17, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtLogin,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txtNom,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														txtPrenom,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														txtPwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														btnSelectionerImage))
								.addGap(18, 18, 18)
								.addComponent(pnlImage,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(btnValider))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));


		//pack();
		btnValider.addActionListener(new Connecter(this.mode));
	}// </editor-fold>

	private void btnSelectionerImageActionPerformed(
			java.awt.event.ActionEvent evt) {
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"JPG & GIF Images", "jpg", "gif");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(null);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println("You chose to open this file: "
					+ chooser.getSelectedFile().getName());
			
			chemin = chooser.getSelectedFile().toString();
			affecterImage(chemin);

		}
	}

	/**
	 * 
	 */
	public void affecterImage(String chemin) {
		ImageIcon img = new ImageIcon(chemin);
		Image img2 = img.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);
		jLabel7.setIcon(new ImageIcon(img2));
		jLabel7.repaint();
		pnlImage.repaint();
		this.repaint();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UserCompte.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UserCompte.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UserCompte.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UserCompte.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserCompte(1).setVisible(true);
			}
		});
		

	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnSelectionerImage;
	private javax.swing.JButton btnValider;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel pnlImage;
	private javax.swing.JTextField txtLogin;
	private javax.swing.JTextField txtNom;
	private javax.swing.JTextField txtPrenom;
	private javax.swing.JTextField txtPwd;
	// End of variables declaration
	
	/********************* Action des boutons *********************/
	public class Connecter extends AbstractAction {
		public Connecter( int mode) {
			super();
		}

		public void actionPerformed(ActionEvent e) {

			
			if (mode == 1) {

				// Vérifier les saisies
				if (txtPwd.getText().equals("") ) {
					JOptionPane.showMessageDialog(null,
							"Vous devez saisir un Login.", "Inane error",
							JOptionPane.ERROR_MESSAGE);
					return;
				}

				userConnect = new UserImpl(txtLogin.getText(), txtPwd.getText(), txtNom.getText(), txtPrenom.getText(), chemin);
				userConnect.enregistrer();
				
				// Charger le compte de l'utilisateur
				userConnect.charger(userConnect.getLogin(), userConnect.getPwd());
				System.out.println("user charg");

				
			} 

			setVisible(false);
		}

	}

	public class Annuler extends AbstractAction {
		public Annuler(String texte) {
			super(texte);
		}

		public void actionPerformed(ActionEvent e) {
			dispose();
		}
	}
	
	
}
